# Generated by Django 5.2.9 on 2026-01-18 16:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('storage_conditions', models.TextField(blank=True, null=True)),
                ('storage_conditions_en', models.TextField(blank=True, null=True)),
                ('storage_conditions_ru', models.TextField(blank=True, null=True)),
                ('storage_conditions_uk', models.TextField(blank=True, null=True)),
                ('description_info', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('description_info_en', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('description_info_ru', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('description_info_uk', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('packaging_info', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('packaging_info_en', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('packaging_info_ru', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('packaging_info_uk', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('payment_info', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('payment_info_en', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('payment_info_ru', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('payment_info_uk', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('delivery_info', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('delivery_info_en', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('delivery_info_ru', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
                ('delivery_info_uk', wagtail.fields.StreamField([('image_with_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('text', 1)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Product common page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
