# Generated by Django 5.2.9 on 2026-01-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpage',
            options={'verbose_name': 'Product page'},
        ),
    ]
