# Generated by Django 5.2.9 on 2026-01-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcommonsettings',
            options={'verbose_name': 'Product common settings'},
        ),
    ]
