# Generated by Django 5.2.9 on 2026-02-09 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название особенности')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='Название особенности')),
                ('name_ru', models.CharField(max_length=64, null=True, verbose_name='Название особенности')),
                ('name_uk', models.CharField(max_length=64, null=True, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Особенность товара',
                'verbose_name_plural': 'Особенности товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Название товара')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='Название товара')),
                ('name_ru', models.CharField(max_length=120, null=True, verbose_name='Название товара')),
                ('name_uk', models.CharField(max_length=120, null=True, verbose_name='Название товара')),
                ('sku', models.CharField(max_length=24, unique=True, verbose_name='Артикул (SKU)')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)])),
                ('calories', models.PositiveIntegerField(verbose_name='Калорийность (на 100г)')),
                ('shelf_life_months', models.PositiveSmallIntegerField(verbose_name='Срок годности (мес.)')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('ingredients_en', models.TextField(null=True, verbose_name='Состав')),
                ('ingredients_ru', models.TextField(null=True, verbose_name='Состав')),
                ('ingredients_uk', models.TextField(null=True, verbose_name='Состав')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('features', models.ManyToManyField(blank=True, to='products.productfeature', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
