# Generated by Django 5.2.9 on 2026-02-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_slug_alter_product_slug_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_uk',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
