# Generated by Django 5.2.9 on 2026-01-06 19:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'verbose_name': 'Gallery page'},
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='content',
            field=wagtail.fields.StreamField([('video', 0), ('image_with_text', 4), ('video_jumbotron', 6)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('title', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 2), ('text_above_play_button', 5), ('text_below_play_button', 5)]], {})}),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}),
        ),
    ]
