# Generated by Django 5.2.9 on 2026-02-14 15:57

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_address_city_alter_address_street_address_and_more'),
        ('products', '0004_alter_product_weight'),
        ('users', '0003_customerprofile_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PAID', 'Оплачен'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='NEW', max_length=10, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('LIQPAY', 'Liqpay'), ('BANK_TRANSFER', 'Банковский перевод'), ('CASH_ON_DELIVERY', 'Наложенный платеж')], max_length=16, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('NOVA_POSHTA', 'Новая Почта'), ('COURIER', 'Курьер'), ('PICKUP', 'Самовывоз')], max_length=11, verbose_name='Способ доставки')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customerprofile', verbose_name='Покупатель')),
                ('delivery_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country', verbose_name='Страна доставки')),
                ('delivery_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='Регион доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderContactInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(unique=True, validators=[core.validators.ukrainian_phone_validator], verbose_name='Номер телефона')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('LEGAL', 'Юридическое лицо')], max_length=10, verbose_name='Тип покупателя')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
