# Generated by Django 5.2.9 on 2026-02-16 11:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordercheckoutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@domain.com', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+38 (099) 999-99-99', unique=True, validators=[core.validators.ukrainian_phone_validator], verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='OrderContactInformation',
        ),
    ]
