# Generated by Django 5.2.9 on 2026-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_company_name_order_contact_person_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('PAID', 'Оплачен'), ('FAILED', 'Провален'), ('SHIPPED', 'Отправлен'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='NEW', max_length=10, verbose_name='Статус'),
        ),
    ]
