# Generated by Django 5.2.9 on 2026-02-18 13:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+38 (099) 999-99-99', validators=[core.validators.ukrainian_phone_validator], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('FAILED', 'Провален'), ('PAID', 'Оплачен'), ('SHIPPED', 'Отправлен'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='NEW', max_length=10, verbose_name='Статус'),
        ),
    ]
