# Generated by Django 5.2.9 on 2026-01-07 11:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_and_delivery', '0002_paymentanddeliverypage_delivery_info_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='delivery_info',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='delivery_info_en',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='delivery_info_ru',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='delivery_info_uk',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='payment_info',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='payment_info_en',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='payment_info_ru',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='payment_info_uk',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='return_info',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='return_info_en',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='return_info_ru',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='paymentanddeliverypage',
            name='return_info_uk',
            field=wagtail.fields.StreamField([('info_section_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
    ]
