# Generated by Django 5.2.9 on 2026-01-13 16:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('video_hero', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})})),
                ('video_hero_en', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('video_hero_ru', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('video_hero_uk', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('products_title', models.CharField(blank=True, max_length=100)),
                ('products_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('products_title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('products_title_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('products_subtitle', models.TextField(blank=True)),
                ('products_subtitle_en', models.TextField(blank=True, null=True)),
                ('products_subtitle_ru', models.TextField(blank=True, null=True)),
                ('products_subtitle_uk', models.TextField(blank=True, null=True)),
                ('video_hero_2', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})})),
                ('video_hero_2_en', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('video_hero_2_ru', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('video_hero_2_uk', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('product_utility_title', models.CharField(blank=True, max_length=100)),
                ('product_utility_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('product_utility_title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('product_utility_title_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('product_utility_description', models.TextField(blank=True)),
                ('product_utility_description_en', models.TextField(blank=True, null=True)),
                ('product_utility_description_ru', models.TextField(blank=True, null=True)),
                ('product_utility_description_uk', models.TextField(blank=True, null=True)),
                ('walnut_utility_description', models.TextField(blank=True)),
                ('walnut_utility_description_en', models.TextField(blank=True, null=True)),
                ('walnut_utility_description_ru', models.TextField(blank=True, null=True)),
                ('walnut_utility_description_uk', models.TextField(blank=True, null=True)),
                ('hazelnut_utility_description', models.TextField(blank=True)),
                ('hazelnut_utility_description_en', models.TextField(blank=True, null=True)),
                ('hazelnut_utility_description_ru', models.TextField(blank=True, null=True)),
                ('hazelnut_utility_description_uk', models.TextField(blank=True, null=True)),
                ('rosehip_utility_description', models.TextField(blank=True)),
                ('rosehip_utility_description_en', models.TextField(blank=True, null=True)),
                ('rosehip_utility_description_ru', models.TextField(blank=True, null=True)),
                ('rosehip_utility_description_uk', models.TextField(blank=True, null=True)),
                ('image_hero', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})})),
                ('image_hero_en', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('image_hero_ru', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('image_hero_uk', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
