# Generated by Django 5.2.9 on 2026-01-07 13:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_image_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='image_hero',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_hero_en',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_hero_ru',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image_hero_uk',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_2',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_2_en',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_2_ru',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_2_uk',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_en',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_ru',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_hero_uk',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
    ]
