# Generated by Django 5.2.9 on 2026-02-01 19:01

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.ukrainian_phone_validator], verbose_name='Номер телефона')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Согласие с условиями')),
                ('is_fop', models.BooleanField(default=False, verbose_name='Является ли ФОП')),
                ('contact_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_contacts', to='locations.address', verbose_name='Контактный адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('LEGAL_ENTITY', 'Юридическое лицо'), ('FOP', 'ФОП')], default='LEGAL_ENTITY', max_length=16, verbose_name='Тип бизнеса')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='users.customerprofile', verbose_name='Профиль клиента')),
            ],
            options={
                'verbose_name': 'Бизнес профиль',
                'verbose_name_plural': 'Бизнес профили',
            },
        ),
        migrations.CreateModel(
            name='FOPDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpo_code', models.CharField(max_length=32, verbose_name='Код ЕГРПОУ')),
                ('activity_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fop_activities', to='locations.address', verbose_name='Адрес деятельности')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fop_details', to='users.businessprofile', verbose_name='Бизнес профиль')),
            ],
            options={
                'verbose_name': 'Детали ФОП',
                'verbose_name_plural': 'Детали ФОП',
            },
        ),
        migrations.CreateModel(
            name='LegalEntityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo_code', models.CharField(max_length=32, verbose_name='Код ОКПО')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_details', to='users.businessprofile', verbose_name='Бизнес профиль')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='locations.address', verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Детали юр. лица',
                'verbose_name_plural': 'Детали юр. лиц',
            },
        ),
    ]
