# Generated by Django 5.2.9 on 2026-02-02 11:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(unique=True, validators=[core.validators.ukrainian_phone_validator], verbose_name='Номер телефона'),
        ),
    ]
