# Generated by Django 5.2.9 on 2026-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Компания'),
        ),
    ]
