# Generated by Django 5.2.9 on 2026-01-07 12:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})})),
                ('hero_en', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('hero_ru', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('hero_uk', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('nut_title', models.CharField(blank=True, max_length=100)),
                ('nut_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('nut_title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('nut_title_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('nut_description', models.TextField(blank=True)),
                ('nut_description_en', models.TextField(blank=True, null=True)),
                ('nut_description_ru', models.TextField(blank=True, null=True)),
                ('nut_description_uk', models.TextField(blank=True, null=True)),
                ('gallery', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('gallery_en', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('gallery_ru', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('gallery_uk', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
            ],
            options={
                'verbose_name': 'Shop page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
