# Generated by Django 5.2.9 on 2026-02-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shoppage_hero_alter_shoppage_hero_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppage',
            name='gallery_en',
        ),
        migrations.RemoveField(
            model_name='shoppage',
            name='gallery_ru',
        ),
        migrations.RemoveField(
            model_name='shoppage',
            name='gallery_uk',
        ),
    ]
