# Generated by Django 5.2.9 on 2026-01-05 10:13

import core.validators
import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('header_text', models.CharField(blank=True, max_length=100)),
                ('header_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('header_text_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('header_text_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Company settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('viber_url', models.URLField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.ukrainian_phone_validator])),
                ('phone_1', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.ukrainian_phone_validator])),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.ukrainian_phone_validator])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('office_and_sales_department_address', models.TextField(blank=True, null=True)),
                ('office_and_sales_department_address_en', models.TextField(blank=True, null=True)),
                ('office_and_sales_department_address_ru', models.TextField(blank=True, null=True)),
                ('office_and_sales_department_address_uk', models.TextField(blank=True, null=True)),
                ('production_address', models.TextField(blank=True, null=True)),
                ('production_address_en', models.TextField(blank=True, null=True)),
                ('production_address_ru', models.TextField(blank=True, null=True)),
                ('production_address_uk', models.TextField(blank=True, null=True)),
                ('map_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Contact settings',
            },
        ),
        migrations.CreateModel(
            name='DiscountBannerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('text_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('text_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Discount banner settings',
            },
        ),
        migrations.CreateModel(
            name='StatisticsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('value', 0), ('unit', 0), ('label', 0)]], {})})),
                ('items_en', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('value', 0), ('unit', 0), ('label', 0)]], {})}, null=True)),
                ('items_ru', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('value', 0), ('unit', 0), ('label', 0)]], {})}, null=True)),
                ('items_uk', wagtail.fields.StreamField([('item', 1)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('value', 0), ('unit', 0), ('label', 0)]], {})}, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Statistics settings',
            },
        ),
    ]
