# Generated by Django 5.2.9 on 2026-02-04 15:40

import auth.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersHistoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Orders history page',
            },
            bases=(auth.mixins.CustomerProfileRequiredMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TransactionsHistoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Transactions history page',
            },
            bases=(auth.mixins.CustomerProfileRequiredMixin, 'wagtailcore.page'),
        ),
    ]
