# Generated by Django 5.2.9 on 2026-02-06 11:15

import auth.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_ordershistorypage_transactionshistorypage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Change password page',
            },
            bases=(auth.mixins.CustomerProfileRequiredMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='AddressPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('side_image_title', models.CharField(blank=True, max_length=100, null=True)),
                ('side_image_title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('side_image_title_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('side_image_title_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('side_image_description', models.TextField(blank=True)),
                ('side_image_description_en', models.TextField(blank=True, null=True)),
                ('side_image_description_ru', models.TextField(blank=True, null=True)),
                ('side_image_description_uk', models.TextField(blank=True, null=True)),
                ('side_image_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('side_image_photo_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('side_image_photo_ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('side_image_photo_uk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Address page',
            },
            bases=(auth.mixins.CustomerProfileRequiredMixin, 'wagtailcore.page'),
        ),
    ]
