# Generated by Django 5.2.9 on 2026-02-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_changepasswordpage_addresspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresspage',
            name='side_image_photo_en',
        ),
        migrations.RemoveField(
            model_name='addresspage',
            name='side_image_photo_ru',
        ),
        migrations.RemoveField(
            model_name='addresspage',
            name='side_image_photo_uk',
        ),
    ]
