# Generated by Django 5.2.9 on 2026-02-17 09:41

import auth.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_addresspage_side_image_photo_en_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Order detail page',
            },
            bases=(auth.mixins.CustomerProfileRequiredMixin, 'wagtailcore.page'),
        ),
    ]
