# Generated by Django 5.2.9 on 2026-01-13 16:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUsePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField()),
                ('description_en', wagtail.fields.RichTextField(null=True)),
                ('description_ru', wagtail.fields.RichTextField(null=True)),
                ('description_uk', wagtail.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Terms of use page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
