# Generated by Django 5.2.9 on 2026-02-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код страны')),
                ('name', models.CharField(max_length=128, verbose_name='Название страны')),
                ('name_en', models.CharField(max_length=128, null=True, verbose_name='Название страны')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Название страны')),
                ('name_uk', models.CharField(max_length=128, null=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название региона/области')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название региона/области')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название региона/области')),
                ('name_uk', models.CharField(max_length=255, null=True, verbose_name='Название региона/области')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код региона')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='locations.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('street_address', models.CharField(max_length=255, verbose_name='Улица, дом, кв.')),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Почтовый индекс')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
