# Generated by Django 5.2.9 on 2026-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=100, verbose_name='Улица, дом, кв.'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название региона/области'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название региона/области'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название региона/области'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_uk',
            field=models.CharField(max_length=30, null=True, verbose_name='Название региона/области'),
        ),
    ]
