# Generated by Django 5.2.9 on 2026-01-13 16:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('hero', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})})),
                ('hero_en', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('hero_ru', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('hero_uk', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('videos', wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})})),
                ('videos_en', wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})}, null=True)),
                ('videos_ru', wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})}, null=True)),
                ('videos_uk', wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})}, null=True)),
                ('owner_cite', models.CharField(blank=True, max_length=255)),
                ('owner_cite_en', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_cite_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_cite_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_description', models.TextField(blank=True)),
                ('owner_description_en', models.TextField(blank=True, null=True)),
                ('owner_description_ru', models.TextField(blank=True, null=True)),
                ('owner_description_uk', models.TextField(blank=True, null=True)),
                ('write_us', models.URLField(blank=True)),
                ('write_us_en', models.URLField(blank=True, null=True)),
                ('write_us_ru', models.URLField(blank=True, null=True)),
                ('write_us_uk', models.URLField(blank=True, null=True)),
                ('company_history_title', models.CharField(blank=True, max_length=255)),
                ('company_history_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('company_history_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('company_history_title_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('company_history_description', models.TextField(blank=True)),
                ('company_history_description_en', models.TextField(blank=True, null=True)),
                ('company_history_description_ru', models.TextField(blank=True, null=True)),
                ('company_history_description_uk', models.TextField(blank=True, null=True)),
                ('image_hero', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})})),
                ('image_hero_en', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('image_hero_ru', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('image_hero_uk', wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True)),
                ('owner_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
