# Generated by Django 5.2.9 on 2026-01-06 23:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='videos',
            field=wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})}),
        ),
        migrations.DeleteModel(
            name='AboutPageVideo',
        ),
    ]
