# Generated by Django 5.2.9 on 2026-01-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_image_hero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='write_us',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='write_us_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='write_us_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='write_us_uk',
        ),
    ]
