# Generated by Django 5.2.9 on 2026-01-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_aboutpage_write_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='videos_en',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='videos_ru',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='videos_uk',
        ),
    ]
