# Generated by Django 5.2.9 on 2026-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutpage_videos_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='owner_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='owner_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='owner_name_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
