# Generated by Django 5.2.9 on 2026-01-07 13:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='hero',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='hero_en',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='hero_ru',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='hero_uk',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='image_hero',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='image_hero_en',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='image_hero_ru',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='image_hero_uk',
            field=wagtail.fields.StreamField([('image_jumbotron', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('text', 2), ('show_top_image', 3)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
    ]
