# Generated by Django 5.2.9 on 2026-01-14 14:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='confectionary_bakeries_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='fitness_clubs_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='horeca_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='retail_stores_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_en',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_ru',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='customerspage',
            name='supermarkets_uk',
            field=wagtail.fields.StreamField([('customer_info_block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('description', 1)]], {})}, null=True),
        ),
    ]
