# Generated by Django 5.2.9 on 2026-02-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_text', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_text_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_text_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('button_text_uk', models.CharField(blank=True, max_length=100, null=True)),
                ('background_image_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
