# Generated by Django 5.2.9 on 2026-01-13 16:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField()),
                ('main_media', wagtail.fields.StreamField([('video', 0), ('image', 1)], block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('body_en', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('body_ru', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
                ('body_uk', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True)),
            ],
            options={
                'verbose_name': 'News detail page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uk', models.TextField(blank=True, null=True)),
                ('hero', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})})),
                ('hero_en', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('hero_ru', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
                ('hero_uk', wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'News index page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
