# Generated by Django 5.2.9 on 2026-01-07 10:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetailpage',
            name='body_en',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='body_ru',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='body_uk',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='hero_en',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='hero_ru',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='hero_uk',
            field=wagtail.fields.StreamField([('video_jumbotron', 3)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('video', 0), ('title', 1), ('text_above_play_button', 2), ('text_below_play_button', 2)]], {})}, null=True),
        ),
    ]
