# Generated by Django 5.2.9 on 2026-01-20 16:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body_en',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body_ru',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AlterField(
            model_name='newsdetailpage',
            name='body_uk',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
